Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Swiftshop.Database;
using Swiftshop.Models;

namespace Swiftshop.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly SwiftshopDbContext _context;

        public CategoryController(SwiftshopDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> CreateCategory(string Name)
        {
            var context = _context.Categories;

            if (!ModelState.IsValid)
            {
                TempData["CreateError"] = "Category name cannot be empty.";
                return RedirectToAction("ManageCategories", "Admin");
            }

            else if (context.Select(c => c.Name).Contains(Name))
            {
                TempData["CreateError"] = "Category name already exists.";
                return RedirectToAction("ManageCategories", "Admin");
            }

            Category NewCategory = new()
            {
                Name = Name
            };

            ViewBag.Prefix = Name;
            await _context.Categories.AddAsync(NewCategory);
            _context.SaveChanges();

            return RedirectToAction("ManageCategories", "Admin", new { Prefix = Name });
        }

        public async Task<IActionResult> DeleteCategory(string CategoryId)
        {
            var context = _context.Categories;
            var DeletedCategory = await context.FirstAsync(c => c.Id == CategoryId);

            _context.Categories.Remove(DeletedCategory);
            await _context.SaveChangesAsync();

            return RedirectToAction("ManageCategories", "Admin");
        }

        public async Task<IActionResult> UpdateCategoryName(string CategoryId, string Name)
        {
            var context = _context.Categories;
            var UpdatedCategory = context.First(c => c.Id == CategoryId);

            if (!ModelState.IsValid)
            {
                Dictionary<string, string> UpdateError = new()
                {
                    { CategoryId, "Category name cannot be null" }
                };

                TempData["UpdateError"] = UpdateError;
                return RedirectToAction("ManageCategories", "Admin", new { Prefix = UpdatedCategory.Name });
            }

            else if (context.Select(c => c.Name).Contains(Name))
            {
                Dictionary<string, string> UpdateError = new()
                {
                    { CategoryId, "Category name already exists." }
                };
                TempData["UpdateError"] = UpdateError;
                return RedirectToAction("ManageCategories", "Admin", new { Prefix = UpdatedCategory.Name });
            }


            UpdatedCategory.Name = Name;

            ViewBag.Prefix = Name;
            _context.Categories.Update(UpdatedCategory);
            await _context.SaveChangesAsync();

            return RedirectToAction("ManageCategories", "Admin", new { Prefix = Name });
        }
    }
}

Controllers/SubcategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swiftshop.Database;
using Swiftshop.Models;

namespace Swiftshop.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SubcategoryController : Controller
    {
        private readonly SwiftshopDbContext _context;

        public SubcategoryController(SwiftshopDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> CreateSubcategory(string Name, string CategoryName)
        {
            var SubcategoryContext = _context.Subcategories;
            var CategoryContext = _context.Categories;

            if (!ModelState.IsValid)
            {
                TempData["CreateError"] = "Subcategory name cannot be null";
                return RedirectToAction("ManageSubcategories", "Admin", new { CategoryId = 0 });
            }

            else if (SubcategoryContext.Select(sc => sc.Name).ToList().Contains(Name))
            {
                TempData["CreateError"] = "Subcategory name already exists.";
                return RedirectToAction("ManageSubcategories", "Admin", new { CategoryId = 0 });
            }

            var NewCategory = CategoryContext.First(c => c.Name == CategoryName);

            Subcategory NewSubcategory = new()
            {
                Name = Name,
                CategoryId = NewCategory.Id,
                Category = NewCategory
            };

            await _context.AddAsync(NewSubcategory);
            _context.SaveChanges();

            return RedirectToAction("ManageSubcategories", "Admin", new { CategoryId = 0, Prefix = NewSubcategory.Name });
        }

        public async Task<IActionResult> DeleteSubcategory(string SubcategoryId)
        {
            var context = _context.Subcategories;
            var DeletedSubcategory = context.First(sc => sc.Id == SubcategoryId);

            _context.Subcategories.Remove(DeletedSubcategory);
            await _context.SaveChangesAsync();

            return RedirectToAction("ManageSubcategories", "Admin", new { DeletedSubcategory.CategoryId, Prefix = DeletedSubcategory.Name });
        }

        public async Task<IActionResult> UpdateSubcategoryName(string SubcategoryId, string Name)
        {
            var context = _context.Subcategories;
            var UpdatedSubcategory = context.First(sc => sc.Id == SubcategoryId);

            if (!ModelState.IsValid)
            {
                Dictionary<string, string> UpdateError = new()
                {
                    {SubcategoryId, "Subcategory name cannot be null."}
                };
                TempData["UpdateError"] = UpdateError;
                return RedirectToAction("ManageSubcategories", "Admin", new {CategoryId = 0, Prefix = UpdatedSubcategory.Name});
            }

            else if (context.Select(c => c.Name).ToList().Contains(Name))
            {
                Dictionary<string, string> UpdateError = new()
                {
                    {SubcategoryId, "Subcategory name already exists."}
                };
                TempData["UpdateError"] = UpdateError;
                return RedirectToAction("ManageSubcategories", "Admin", new {CategoryId = 0, Prefix= UpdatedSubcategory.Name});
            }

            
            UpdatedSubcategory.Name = Name;

            _context.Subcategories.Update(UpdatedSubcategory);
            await _context.SaveChangesAsync();

            return RedirectToAction("ManageSubcategories", "Admin", new {CategoryId = 0, Prefix = UpdatedSubcategory.Name});
        }

        public async Task<IActionResult> UpdateSubcategoryCategory(string SubcategoryId, string NewCategoryName)
        {
            var SubcategoryContext = _context.Subcategories;
            var CategoryContext = _context.Categories;

            if (!CategoryContext.Select(c => c.Name).ToList().Contains(NewCategoryName))
            {
                return RedirectToAction("ManageSubcategories", "Admin", new { CategoryId = 0});
            }

            var NewCategory = CategoryContext.First(c => c.Name == NewCategoryName);

            var UpdatedSubcategory = SubcategoryContext.First(sc => sc.Id == SubcategoryId);
            UpdatedSubcategory.Category = NewCategory;
            UpdatedSubcategory.CategoryId = NewCategory.Id;

            _context.Subcategories.Update(UpdatedSubcategory);
            await _context.SaveChangesAsync();

            return RedirectToAction("ManageSubcategories", "Admin", new {UpdatedSubcategory.CategoryId});
        }
    }
}

Views/Admin/Index.cshtml
<div class="d-flex justify-content-center mt-5">
    <div class="d-inline-flex mt-4 mb-5">
        <div class="card admin-route-card me-5" style="width: 25rem;">
            <img src="~/admin-category.png" class="card-img-top mt-5 mx-auto my-auto" style="width:90%">
            <div class="card-body" style="background-color:#212121">
                <h3 class="card-title site-head-text mb-3">Categories</h3>
                <p class="card-text site-text">Add new categories or remove and make changes on existing categories.</p>
                <a asp-action="ManageCategories" class="btn btn-light site-text-inv">Manage</a>
            </div>
        </div>
        <div class="card admin-route-card me-5 ms-5" style="width: 25rem;">
            <img src="~/admin-subcategory.png" class="card-img-top mt-5 mx-auto my-auto" style="width:90%">
            <div class="card-body" style="background-color:#212121">
                <h3 class="card-title site-head-text mb-3">Subcategories</h3>
                <p class="card-text site-text">Add new subcategories or remove and make changes on existing subcategories.</p>
                <a asp-action="ManageSubcategories" asp-route-CategoryId="0" class="btn btn-light site-text-inv">Manage</a>
            </div>
        </div>
        <div class="card admin-route-card ms-5" style="width: 25rem;">
            <img src="~/admin-product.png" class="card-img-top mt-5 mx-auto my-auto" style="width:90%">
            <div class="card-body" style="background-color:#212121">
                <h3 class="card-title site-head-text mb-3">Products</h3>
                <p class="card-text site-text">Add new products to be listed or remove and make changes on existing products.</p>
                <a asp-action="ManageProducts" asp-route-SubcategoryId="0" class="btn btn-light site-text-inv">Manage</a>
            </div>
        </div>
    </div>
</div>

Views/Admin/ManageCategories.cshtml
@model Swiftshop.Models.Category;

@{
    List<Category> Categories = ViewBag.Categories as List<Category>;
    var CreateError = TempData["CreateError"] as string;
    var UpdateError = TempData["UpdateError"] as Dictionary<string, string>;
    var Prefix = ViewBag.Prefix as string;
}

<div class="container-fluid">
    <div class="list-page-navbar site-text mx-auto" style="width:85%">
        <div class="d-flex flex-column mt-2 mb-2 ms-4 me-4">
            <h1>Create New Category</h1>
            <h5>Categories contain subcategories to enhance product searching.</h5>
            <div class="d-inline-flex justify-content-between">
                <!--Create Category Section-->
                <form class="mt-2" asp-controller="Category" asp-action="CreateCategory">
                    <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                    <div class="input-group mb-2">
                        <input asp-for="Name" class="form-control" placeholder="New Category" aria-label="New Category" aria-describedby="basic-addon2">
                        <button type="submit" class="btn btn-light">Create</button>
                    </div>
                    <span asp-validation-for="Name" class="text-danger">@CreateError</span>
                </form>
                <!--Category Prefix Search-->
                <form class="mt-2" asp-controller="Admin" asp-action="ManageCategories" asp-route-Prefix="@Prefix">
                    <div class="input-group">
                        <input type="text" class="form-control" name="Prefix" value="@Prefix">
                        <button class="btn btn-light" type="submit"><i class="bi bi-search"></i> Search</button>
                        @{
                            if (Prefix != "")
                            {
                                <a class="btn btn-light" asp-action="ManageCategories" asp-route-Prefix="">Clear</a>
                            }
                        }
                    </div>
                </form>
            </div>
        </div>
    </div>
    @{
        if (Categories.Count != 0)
        {
            <div class="mx-auto mt-4" style="height:55vh; width:84%; overflow-y:auto; overflow-x:hidden">
                <table class="table align-middle table-borderless me-5">
                    <tbody>
                        @{
                            foreach (var category in Categories)
                            {
                                <tr>
                                    <td class="site-text"><h5>@category.Name</h5></td>
                                    <td class="site-text"><h5>@category.Id</h5></td>
                                    <td>
                                        <form class="mt-4 mb-4" asp-controller="Category" asp-action="UpdateCategoryName" asp-route-CategoryId="@category.Id">
                                            <div class="d-flex flex-column site-text">
                                                <div class="input-group">
                                                    <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                                                    <input asp-for="Name" class="form-control" placeholder="Update Category Name">
                                                    <button type="submit" class="btn btn-dark site-button">Update</button>
                                                    <a class="btn btn-md btn-dark site-button ms-5" asp-controller="Category" asp-action="DeleteCategory" asp-route-CategoryId="@category.Id">Delete <i class="bi bi-trash"></i></a>
                                                </div>
                                                <div>
                                                    @{
                                                        if (UpdateError != null && UpdateError.ContainsKey(category.Id))
                                                        {
                                                            <span asp-validation-for="Name" class="text-danger">@UpdateError[category.Id]</span>
                                                        }
                                                    }
                                                </div>
                                            </div>
                                        </form>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <div class="d-flex justify-content-center">
                <img class="mt-5" src="/no-content.png" style="width:30%" />
            </div>
        }
    }
</div>

Views/Admin/ManageSubcategories.cshtml
@model Swiftshop.Models.Subcategory

@{
    var Subcategories = ViewBag.Subcategories as List<Subcategory>;
    var Categories = ViewBag.Categories as List<Category>;

    var CreateError = TempData["CreateError"] as string;
    var UpdateError = TempData["UpdateError"] as Dictionary<string, string>;

    string Prefix = ViewBag.Prefix;
    string CategoryId = ViewBag.CategoryId;
}

<div class="container-fluid">
    @{
        if (Categories.Count > 0)
        {
            <div class="d-flex flex-column mx-auto" style="width:85%">
                <div class="list-page-navbar site-text">
                    @*Create Subcategory Section*@
                    <form class="mt-2 mb-3 ms-4 me-4 " asp-controller="Subcategory" asp-action="CreateSubcategory">
                        <div>
                            <h1>Create New Subcategory</h1>
                            <h5>Subcategories contain products and has a main category to enhance product searching.</h5>
                        </div>
                        <div class="d-flex mb-2 w-75">
                            <div class="input-group me-2">
                                <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                                <span class="input-group-text">Subcategory Name</span>
                                <input class="form-control" asp-for="Name" />
                            </div>
                            <div class="input-group">
                                <span class="input-group-text">Parent Category</span>
                                <select required class="form-select" id="CategoryName" name="CategoryName">
                                    <option selected value="@Categories.First().Name">@Categories.First().Name</option>
                                    @{
                                        var TempCategory = Categories.First();
                                        Categories.Remove(Categories.First());
                                        foreach (var category in Categories)
                                        {
                                            <option value="@category.Name">@category.Name</option>
                                        }
                                        Categories.Insert(0, TempCategory);
                                    }
                                </select>
                            </div>
                        </div>
                        <span asp-validation-for="Name" class="text-danger mt-1 mb-3">@CreateError</span>
                        <div class="input-group mt-3"><input type="submit" class="btn btn-md btn-light" value="Create" /></div>
                    </form>
                </div>
                <div class="d-inline-flex mt-5">
                    @*Sidebar Section*@
                    <div class="d-flex flex-column site-text me-5">
                        <form class="mb-4" asp-controller="Admin" asp-action="ManageSubcategories" asp-route-CategoryId="@CategoryId">
                            <div class="input-group">
                                <input type="text" class="form-control" name="Prefix" value="@Prefix">
                                <button class="btn btn-dark site-button" type="submit"><i class="bi bi-search"></i> Search</button>
                            </div>
                            @{
                                if (CategoryId != "0" || Prefix != "")
                                {
                                    <a class="btn btn-dark site-button mt-2" asp-controller="Admin" asp-action="ManageSubcategories" asp-route-CategoryId="0">Clear Search</a>
                                }
                            }
                        </form>
                        <div style="height:44vh; overflow-y:auto">
                            @{
                                foreach (var category in Categories)
                                {
                                    <div class="mb-4"><a class="site-text" asp-controller="Admin" asp-action="ManageSubcategories" asp-route-CategoryId="@category.Id" style="text-decoration:none"><h5>@category.Name</h5></a></div>
                                }
                            }
                        </div>
                    </div>
                    <div class="flex-grow-1">
                        @{
                            //Update Subcategory Section
                            if (Subcategories.Count > 0)
                            {
                                <div style="height:50vh; overflow-y:auto">
                                    <table class="table align-middle table-borderless site-text">
                                        <tbody class="table-group-divider">
                                            @{
                                                foreach (var subcategory in Subcategories)
                                                {
                                                    <tr>
                                                        <td><h5>@subcategory.Category.Name => @subcategory.Name</h5></td>
                                                        <td>
                                                            <div class="d-flex justify-content-between mt-4 mb-4">
                                                                <div class="d-flex flex-column flex-grow-1">
                                                                    @* Update Subcategory Name Form *@
                                                                    <form asp-controller="Subcategory" asp-action="UpdateSubcategoryName" asp-route-SubcategoryId="@subcategory.Id">
                                                                        <div class="d-flex flex-column">
                                                                            <div class="input-group mb-1">
                                                                                <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                                                                                <input asp-for="Name" class="form-control" placeholder="Update Subcategory Name">
                                                                                <button type="submit" class="btn btn-dark site-button">Update</button>
                                                                            </div>
                                                                            @{
                                                                                if (UpdateError != null && UpdateError.ContainsKey(subcategory.Id))
                                                                                {
                                                                                    <span asp-validation-for="Name" class="text-danger mb-2">@UpdateError[subcategory.Id]</span>
                                                                                }
                                                                            }
                                                                        </div>
                                                                    </form>
                                                                    @* Update Subcategory Parent Category Form *@
                                                                    <form asp-controller="Subcategory" asp-action="UpdateSubcategoryCategory" asp-route-SubcategoryId="@subcategory.Id">
                                                                        <div class="input-group">
                                                                            <select class="form-select" id="NewCategoryName" name="NewCategoryName">
                                                                                <option selected value="@subcategory.Category.Name">@subcategory.Category.Name</option>
                                                                                @{
                                                                                    foreach (var category in Categories)
                                                                                    {
                                                                                        if (subcategory.Category.Name != category.Name)
                                                                                        {
                                                                                            <option value="@category.Name">@category.Name</option>
                                                                                        }
                                                                                    }
                                                                                }
                                                                            </select>
                                                                            <input type="submit" class="btn btn-md btn-dark site-button" value="Update" />
                                                                        </div>
                                                                    </form>
                                                                    @* Delete Subcategory *@
                                                                </div>
                                                                <a class="btn btn-md btn-dark site-button ms-5 me-5 my-auto" asp-controller="Subcategory" asp-action="DeleteSubcategory" asp-route-SubcategoryId="@subcategory.Id">Delete <i class="bi bi-trash"></i></a>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            }
                            else
                            {
                                <div class="d-flex justify-content-center me-5 pe-5">
                                    <img src="/no-content.png" />
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="d-flex flex-column">
                <h1 class="site-head-text mt-5 mx-auto">No categories are found. Please add new categories to proceed.</h1>
                <img class="w-50 mt-5 mx-auto" src="/404.png" />
            </div>
        }
    }
</div>