Areas/Identity/Pages/_Layout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Swiftshop.Areas.Identity.Pages
{
    public class _LayoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Controllers/ShoppingListController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Swiftshop.Database;
using Swiftshop.Models;
using System.Diagnostics;

namespace Swiftshop.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class ShoppingListController : Controller
    {
        private readonly SwiftshopDbContext _context;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly UserManager<User> _userManager;

        public ShoppingListController(SwiftshopDbContext context, IHttpContextAccessor contextAccessor, UserManager<User> userManager)
        {
            _context = context;
            _contextAccessor = contextAccessor;
            _userManager = userManager;
        }

        public async Task<IActionResult> CreateShoppingList(string NewName)
        {
            var ShoppingListContext = _context.ShoppingLists;

            var CurrentUser = await _userManager.FindByEmailAsync(_contextAccessor.HttpContext.User.Identity.Name);

            var ActiveListsOfUser = _context.ShoppingLists
                .Where(al => al.UserId == CurrentUser.Id && al.IsActive == true)
                .Select(al => al.Name)
                .ToList();

            ShoppingList NewList = new()
            {
                Name = NewName,
                UserId = CurrentUser.Id,
                User = CurrentUser
            };

            await _context.AddAsync(NewList);
            await _context.SaveChangesAsync();

            return RedirectToAction("ActiveLists", new { Page = 1 });
        }

        public async Task<IActionResult> ActiveLists(int Page)
        {
            if (Page == 0)
            {
                ViewBag.Page = 1;
                return RedirectToAction("ActiveLists", new { Page = 1 });
            }

            int PaginatorSize;

            //Get Current User
            var CurrentUser = await _userManager.FindByEmailAsync(_contextAccessor.HttpContext.User.Identity.Name);

            //Fetch all user list newest to oldest.
            var UserLists = await _context.ShoppingLists
                .Where(sl => sl.UserId == CurrentUser.Id && sl.IsActive == true && sl.IsStarted == false)
                .OrderByDescending(sl => sl.CreatedAt)
                .ToListAsync();

            //Calculating the paginator length for paginator component.
            PaginatorSize = UserLists.Count / 3;
            if (UserLists.Count % 3 != 0) { PaginatorSize++; }
            ViewBag.PaginatorSize = PaginatorSize;

            //Fetching up to 3 Shopping Lists per page.
            List<ShoppingList>? PageLists = new();
            for (int i = (Page - 1) * 3; i < Page * 3; i++)
            {
                if (UserLists.Count <= i) { break; } // Null Exception Preventation.

                PageLists.Add(UserLists.ElementAt(i));
            }

            //First ListContent Image for List View
            Dictionary<string, string> ListImages = new();

            foreach (var list in UserLists)
            {
                if (_context.ShoppingListContents.Where(slc => slc.ListId == list.Id).ToList().Count > 0)
                {
                    var ListImage = _context.ShoppingListContents
                    .Where(slc => slc.ListId == list.Id)
                    .Join(_context.Products,
                    slc => slc.ProductId,
                    p => p.Id,
                    (slc, p) => p.ProductImage)
                    .First();

                    ListImages.Add(list.Id, ListImage);
                }

                else
                {
                    ListImages.Add(list.Id, null);
                }
            }

            ViewBag.ListImages = ListImages;
            ViewBag.Page = Page;
            return View(PageLists);
        }

        public async Task<IActionResult> CompletedLists(int Page)
        {
            if (Page == 0) { return RedirectToAction("CompleteLists", new { Page = 1 }); }

            int PaginatorSize;

            var CurrentUser = await _userManager.FindByEmailAsync(_contextAccessor.HttpContext.User.Identity.Name);

            //Fetch all user list in newest to oldest.
            var UserLists = await _context.ShoppingLists
                .Where(sl => sl.UserId == CurrentUser.Id && sl.IsStarted == true && sl.IsActive == true)
                .OrderBy(sl => sl.CreatedAt)
                .ToListAsync();

            //Calculating the paginator length for paginator component.
            PaginatorSize = UserLists.Count / 3;
            if (UserLists.Count % 3 != 0) { PaginatorSize++; }
            ViewBag.PaginatorSize = PaginatorSize;

            //Fetching up to 3 Shopping Lists per page.
            List<ShoppingList>? PageLists = new();
            for (int i = (Page - 1) * 3; i < Page * 3; i++)
            {
                if (UserLists.Count <= i) { break; } // Null Exception Preventation.

                PageLists.Add(UserLists.ElementAt(i));
            }

            //First ListContent Image for List View
            Dictionary<string, string> ListImages = new();

            foreach (var list in UserLists)
            {
                if (_context.ShoppingListContents.Where(slc => slc.ListId == list.Id).ToList().Count > 0)
                {
                    var ListImage = _context.ShoppingListContents
                    .Where(slc => slc.ListId == list.Id)
                    .Join(_context.Products,
                    slc => slc.ProductId,
                    p => p.Id,
                    (slc, p) => p.ProductImage)
                    .First();

                    ListImages.Add(list.Id, ListImage);
                }

                else
                {
                    ListImages.Add(list.Id, null);
                }
            }

            ViewBag.ListImages = ListImages;

            return View(PageLists);

        }

        public async Task<IActionResult> DeleteShoppingList(string ListId, string ReturnAction)
        {
            var CurrentUser = await _userManager.FindByEmailAsync(_contextAccessor.HttpContext.User.Identity.Name);

            var CurrentShoppingList = _context.ShoppingLists.First(sl => sl.Id == ListId && sl.UserId == CurrentUser.Id);

            //Favorite Lists are not deleted and can be retrieved from user profile.
            if (CurrentShoppingList.IsFavorited == true)
            {
                CurrentShoppingList.IsActive = false;
                _context.ShoppingLists.Update(CurrentShoppingList);
                await _context.SaveChangesAsync();
                return RedirectToAction(ReturnAction, new { Page = 1 });
            }

            _context.ShoppingLists.Remove(CurrentShoppingList);
            await _context.SaveChangesAsync();

            return RedirectToAction(ReturnAction, new { Page = 1 });
        }

        //Functionality for adding lists to favorites.
        public async Task<IActionResult> SwitchIsFavorited(string ListId, bool OldStatus, int Page)
        {
            var CurrentUser = await _userManager.FindByEmailAsync(_contextAccessor.HttpContext.User.Identity.Name);

            var ShoppingListContext = _context.ShoppingLists.First(sl => sl.Id == ListId && sl.UserId == CurrentUser.Id).IsFavorited = !OldStatus;

            await _context.SaveChangesAsync();

            return RedirectToAction("ActiveLists", new { Page });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Swiftshop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Swiftshop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://fonts.cdnfonts.com/css/bukhari-script" rel="stylesheet">
</head>
<body class="vh-100">
<div class="d-flex flex-column">
        @*Navbar*@
        <div class="navbar fixed-top">
            <div class="w-100 d-flex align-items-center justify-content-between">
                <div class="mt-3 ms-4" style="width:30%"><a asp-controller="ShoppingList" asp-action="ActiveLists" asp-route-Page="1"><img style="width:30%" src="~/logo.png" /></a></div>
                <div class="mt-1 me-4"><partial name="_LoginPartial" /></div>
            </div>
        </div>
        @*Main Canvas*@
        <div class="container-fluid" style="margin-top:5%">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        @*Footer*@
        <footer class="navbar fixed-bottom justify-content-center" style="color:white">
            <div class="d-flex flex-column ">
                <p class="site-head-text my-auto">Swiftshop © 2023</p>
                <div class="d-inline-flex mx-auto mt-2">
                    <a class="me-2" href="https://github.com/Quiccc/Swiftshop" style="color:#efefef"><i class="bi bi-github"></i></a>
                    <a class="ms-2" href="https://www.linkedin.com/in/skagan4slan/" style="color:#efefef"><i class="bi bi-linkedin"></i></a>
                </div>
            </div>
        </footer>
</div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>