Models/ShoppingList.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Swiftshop.Models
{
    public class ShoppingList
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string? Id { get; set; }
        public string? Name { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsFavorited { get; set; }
        public bool? IsStarted { get; set; }
        public virtual ICollection<ShoppingListContent>? ListContents { get; set; }
        public string? UserId { get; set; }
        public User? User { get; set; }
        public DateTime? CreatedAt { get; set; }

        public ShoppingList()
        {
            ListContents = null;
            IsActive = true;
            IsFavorited = false;
            IsStarted = false;
            CreatedAt = DateTime.Now;
        }
    }
}

Controllers/ShoppingListContentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;
using Swiftshop.Database;
using Swiftshop.Models;
using Swiftshop.Models.DTO;

namespace Swiftshop.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class ShoppingListContentController : Controller
    {
        private readonly SwiftshopDbContext _context;

        public ShoppingListContentController(SwiftshopDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string ListId, string SubcategoryId, string Prefix)
        {
            if (Prefix == null) { Prefix = ""; }

            //Fetch all categories and subcategories for product filtering.
            var SubcategoryContext = _context.Subcategories.ToList();
            var CategoryContext = _context.Categories
                .OrderBy(c => c.Name)
                .ToList();

            ViewBag.ListId = ListId;
            ViewBag.SubcategoryId = SubcategoryId;
            ViewBag.Categories = CategoryContext;
            ViewBag.Prefix = Prefix;

            //No product filtering
            if (SubcategoryId == "0")
            {
                var ProductContext = _context.Products.Where(p => p.Name.Contains(Prefix));
                return View(await ProductContext.ToListAsync());
            }

            //Returns products depending on selected subcategory and prefix.
            else
            {
                var ProductContext = _context.Products.Where(p => p.SubcategoryId == SubcategoryId && p.Name.Contains(Prefix));
                return View(await ProductContext.ToListAsync());
            }
        }

        public async Task<IActionResult> AddProductToList(string ListId, string ProductId, string Description, string SubcategoryId)
        {
            var CurrentListContentContext = _context.ShoppingListContents
                .Where(slc => slc.ListId == ListId && slc.ProductId == ProductId)
                .ToList();

            if (!CurrentListContentContext.IsNullOrEmpty())
            {
                return RedirectToAction("Index", new { ListId, SubcategoryId });
            }

            var CurrentShoppingList = _context.ShoppingLists.Where(sl => sl.Id == ListId).First();
            var AddedProduct = _context.Products.Where(p => p.Id == ProductId).First();

            var ShoppingListContentContext = _context.ShoppingListContents;

            ShoppingListContent NewListContent = new()
            {
                ListId = ListId,
                List = CurrentShoppingList,
                ProductId = ProductId,
                Product = AddedProduct,
                Description = Description
            };

            await _context.AddAsync(NewListContent);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", new { ListId, SubcategoryId });
        }

        public async Task<IActionResult> ActiveListSummary(string ListId)
        {
            //Contents of an active shopping list.
            var ListContent = await _context.ShoppingListContents
                 .Where(slc => slc.ListId == ListId)
                 .Join(
                 _context.Products,
                 slc => slc.ProductId,
                 p => p.Id,
                 (slc, p) => new ActiveListContentDto
                 { ListId = slc.ListId, ProductId = p.Id, ProductName = p.Name, ProductImage = p.ProductImage, Description = slc.Description })
                 .ToListAsync();

            return View(ListContent);
        }

        public async Task<IActionResult> CompletedListSummary(string ListId)
        {
            //Contents of an completed shopping list.
            var ListContent = await _context.ShoppingListContents
                .Where(slc => slc.ListId == ListId)
                .Join(
                _context.Products,
                slc => slc.ProductId,
                p => p.Id,
                (slc, p) => new CompletedListContentDto
                { ListId = slc.ListId, ProductId = p.Id, ProductName = p.Name, ProductImage = p.ProductImage, Description = slc.Description, IsAcquired = slc.IsAcquired })
                .ToListAsync();

            return View(ListContent);
        }

        public async Task<IActionResult> SwitchIsAcquired(string ListId, string ProductId)
        {
            var AcquiredProduct = _context.ShoppingListContents.First(slc => slc.ListId == ListId && slc.ProductId == ProductId);
            AcquiredProduct.IsAcquired = true;

            _context.Update(AcquiredProduct);
            await _context.SaveChangesAsync();

            return RedirectToAction("CompletedListSummary", new { ListId });
        }

        public async Task<IActionResult> UpdateDescription(string ListId, string ProductId, string Description)
        {
            var UpdatedProduct = _context.ShoppingListContents.First(slc => slc.ListId == ListId && slc.ProductId == ProductId);

            if (UpdatedProduct.Description != null && UpdatedProduct.Description.Equals(Description))
            {
                return RedirectToAction("ActiveListSummary", new { ListId });
            }

            UpdatedProduct.Description = Description;
            _context.Update(UpdatedProduct);
            await _context.SaveChangesAsync();

            return RedirectToAction("ActiveListSummary", new { ListId });
        }

        public async Task<IActionResult> DeleteListProduct(string ListId, string ProductId)
        {
            var DeletedProduct = _context.ShoppingListContents.First(slc => slc.ListId == ListId && slc.ProductId == ProductId);
            _context.Remove(DeletedProduct);
            await _context.SaveChangesAsync();

            return RedirectToAction("ActiveListSummary", new { ListId });
        }

        public async Task<IActionResult> StartShopping(string ListId)
        {
            var ShoppingListContext = _context.ShoppingLists.First(sl => sl.Id == ListId).IsStarted = true;
            await _context.SaveChangesAsync();

            return RedirectToAction("CompletedLists", "ShoppingList", new { Page = 1 });
        }

        public async Task<IActionResult> CompleteShopping(string ListId)
        {
            //Change flag to finish shopping process.
            var CurrentList = _context.ShoppingLists.Where(sl => sl.Id == ListId).First();
            CurrentList.IsStarted = false;

            //Get Acquired Products as list
            var AcquiredListContents = _context.ShoppingListContents.Where(slc => slc.ListId == ListId && slc.IsAcquired == true)
                .Join(_context.Products, alc => alc.ProductId, p => p.Id, (alc, p) => new ShoppingListContent { ListId = alc.ListId, Description = alc.Description, IsAcquired = alc.IsAcquired, ProductId = p.Id, Product = p })
                .ToList();

            if (AcquiredListContents.Count > 0)
            {
                //Create a history of the completed list.
                ShoppingListHistory ListHistory = new()
                {
                    Name = CurrentList.Name,
                    ListContents = JsonConvert.SerializeObject(AcquiredListContents.Select(alc => alc.Product.Name), Formatting.Indented, new JsonSerializerSettings
                    {
                        ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                    }),
                    UserId = CurrentList.UserId,
                    User = CurrentList.User
                };
                _context.ShoppingListHistories.Add(ListHistory);
            }

            //Section for favorited lists. Acquired list products does not get removed.
            if (CurrentList.IsFavorited == true)
            {
                foreach (var content in AcquiredListContents)
                {
                    content.IsAcquired = false;
                    _context.ShoppingListContents.Update(content);
                }
            }

            //Section for regular lists. Acquired list products are removed.
            else
            {
                foreach (var content in AcquiredListContents)
                {
                    _context.ShoppingListContents.Remove(content);
                }
            }

            _context.ShoppingLists.Update(CurrentList);
            await _context.SaveChangesAsync();

            return RedirectToAction("ActiveLists", "ShoppingList", new { Page = 1 });
        }
    }
}

Controllers/ShoppingListController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Swiftshop.Database;
using Swiftshop.Models;
using System.Diagnostics;

namespace Swiftshop.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class ShoppingListController : Controller
    {
        private readonly SwiftshopDbContext _context;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly UserManager<User> _userManager;

        public ShoppingListController(SwiftshopDbContext context, IHttpContextAccessor contextAccessor, UserManager<User> userManager)
        {
            _context = context;
            _contextAccessor = contextAccessor;
            _userManager = userManager;
        }

        public async Task<IActionResult> CreateShoppingList(string NewName)
        {
            var ShoppingListContext = _context.ShoppingLists;

            var CurrentUser = await _userManager.FindByEmailAsync(_contextAccessor.HttpContext.User.Identity.Name);

            var ActiveListsOfUser = _context.ShoppingLists
                .Where(al => al.UserId == CurrentUser.Id && al.IsActive == true)
                .Select(al => al.Name)
                .ToList();

            ShoppingList NewList = new()
            {
                Name = NewName,
                UserId = CurrentUser.Id,
                User = CurrentUser
            };

            await _context.AddAsync(NewList);
            await _context.SaveChangesAsync();

            return RedirectToAction("ActiveLists", new { Page = 1 });
        }

        public async Task<IActionResult> ActiveLists(int Page)
        {
            if (Page == 0)
            {
                ViewBag.Page = 1;
                return RedirectToAction("ActiveLists", new { Page = 1 });
            }

            int PaginatorSize;

            //Get Current User
            var CurrentUser = await _userManager.FindByEmailAsync(_contextAccessor.HttpContext.User.Identity.Name);

            //Fetch all user list newest to oldest.
            var UserLists = await _context.ShoppingLists
                .Where(sl => sl.UserId == CurrentUser.Id && sl.IsActive == true && sl.IsStarted == false)
                .OrderByDescending(sl => sl.CreatedAt)
                .ToListAsync();

            //Calculating the paginator length for paginator component.
            PaginatorSize = UserLists.Count / 3;
            if (UserLists.Count % 3 != 0) { PaginatorSize++; }
            ViewBag.PaginatorSize = PaginatorSize;

            //Fetching up to 3 Shopping Lists per page.
            List<ShoppingList>? PageLists = new();
            for (int i = (Page - 1) * 3; i < Page * 3; i++)
            {
                if (UserLists.Count <= i) { break; } // Null Exception Preventation.

                PageLists.Add(UserLists.ElementAt(i));
            }

            //First ListContent Image for List View
            Dictionary<string, string> ListImages = new();

            foreach (var list in UserLists)
            {
                if (_context.ShoppingListContents.Where(slc => slc.ListId == list.Id).ToList().Count > 0)
                {
                    var ListImage = _context.ShoppingListContents
                    .Where(slc => slc.ListId == list.Id)
                    .Join(_context.Products,
                    slc => slc.ProductId,
                    p => p.Id,
                    (slc, p) => p.ProductImage)
                    .First();

                    ListImages.Add(list.Id, ListImage);
                }

                else
                {
                    ListImages.Add(list.Id, null);
                }
            }

            ViewBag.ListImages = ListImages;
            ViewBag.Page = Page;
            return View(PageLists);
        }

        public async Task<IActionResult> CompletedLists(int Page)
        {
            if (Page == 0) { return RedirectToAction("CompleteLists", new { Page = 1 }); }

            int PaginatorSize;

            var CurrentUser = await _userManager.FindByEmailAsync(_contextAccessor.HttpContext.User.Identity.Name);

            //Fetch all user list in newest to oldest.
            var UserLists = await _context.ShoppingLists
                .Where(sl => sl.UserId == CurrentUser.Id && sl.IsStarted == true && sl.IsActive == true)
                .OrderBy(sl => sl.CreatedAt)
                .ToListAsync();

            //Calculating the paginator length for paginator component.
            PaginatorSize = UserLists.Count / 3;
            if (UserLists.Count % 3 != 0) { PaginatorSize++; }
            ViewBag.PaginatorSize = PaginatorSize;

            //Fetching up to 3 Shopping Lists per page.
            List<ShoppingList>? PageLists = new();
            for (int i = (Page - 1) * 3; i < Page * 3; i++)
            {
                if (UserLists.Count <= i) { break; } // Null Exception Preventation.

                PageLists.Add(UserLists.ElementAt(i));
            }

            //First ListContent Image for List View
            Dictionary<string, string> ListImages = new();

            foreach (var list in UserLists)
            {
                if (_context.ShoppingListContents.Where(slc => slc.ListId == list.Id).ToList().Count > 0)
                {
                    var ListImage = _context.ShoppingListContents
                    .Where(slc => slc.ListId == list.Id)
                    .Join(_context.Products,
                    slc => slc.ProductId,
                    p => p.Id,
                    (slc, p) => p.ProductImage)
                    .First();

                    ListImages.Add(list.Id, ListImage);
                }

                else
                {
                    ListImages.Add(list.Id, null);
                }
            }

            ViewBag.ListImages = ListImages;

            return View(PageLists);

        }

        public async Task<IActionResult> DeleteShoppingList(string ListId, string ReturnAction)
        {
            var CurrentUser = await _userManager.FindByEmailAsync(_contextAccessor.HttpContext.User.Identity.Name);

            var CurrentShoppingList = _context.ShoppingLists.First(sl => sl.Id == ListId && sl.UserId == CurrentUser.Id);

            //Favorite Lists are not deleted and can be retrieved from user profile.
            if (CurrentShoppingList.IsFavorited == true)
            {
                CurrentShoppingList.IsActive = false;
                _context.ShoppingLists.Update(CurrentShoppingList);
                await _context.SaveChangesAsync();
                return RedirectToAction(ReturnAction, new { Page = 1 });
            }

            _context.ShoppingLists.Remove(CurrentShoppingList);
            await _context.SaveChangesAsync();

            return RedirectToAction(ReturnAction, new { Page = 1 });
        }

        //Functionality for adding lists to favorites.
        public async Task<IActionResult> SwitchIsFavorited(string ListId, bool OldStatus, int Page)
        {
            var CurrentUser = await _userManager.FindByEmailAsync(_contextAccessor.HttpContext.User.Identity.Name);

            var ShoppingListContext = _context.ShoppingLists.First(sl => sl.Id == ListId && sl.UserId == CurrentUser.Id).IsFavorited = !OldStatus;

            await _context.SaveChangesAsync();

            return RedirectToAction("ActiveLists", new { Page });
        }
    }
}

Views/ShoppingList/ActiveLists.cshtml
@model List<Swiftshop.Models.ShoppingList>
@{
    ViewData["Title"] = "Home Page";
    Dictionary<string, string> ListImages = ViewBag.ListImages;
}

<div class="container">
    <div class="d-flex flex-column">
        <div class="d-inline-flex justify-content-between mb-5 list-page-navbar">
            <div class="d-inline-flex mt-4 mb-4 ms-4">
                <div><h2 class="site-text">Active Shopping Lists</h2></div>
                @*Create List Modal Button*@
                <button type="button" class="btn btn-sm btn-light ms-4 site-text-inv-lg" data-bs-toggle="modal" data-bs-target="#CreateListModal">New Shopping List</button>
                <div>
                    @*Create List Modal*@
                    <div class="modal fade site-text" id="CreateListModal" tabindex="-1" aria-labelledby="CreateListModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content list-page-modal" style="background-color:#212121">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="CreateListModalLabel">Name Your Shopping List.</h1>
                                    <button type="button" class="btn btn-dark" data-bs-dismiss="modal" aria-label="Close"><i class="bi bi-x-lg"></i></button>
                                </div>
                                <div class="modal-body">
                                    <form asp-controller="ShoppingList" asp-action="CreateShoppingList" style="margin-top:2%; width:100%">
                                        <div class="input-group mb-3">
                                            <input required type="text" name="NewName" class="form-control" placeholder="New Shopping List" aria-label="New Shopping List" aria-describedby="basic-addon2">
                                        </div>
                                        <button type="submit" class="btn btn-light">Create</button>
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--List Type Navigation Bar-->
            <ul class="nav my-auto">
                <li class="nav-item">
                    <a class="nav-link disabled site-text-lg" aria-disabled="true">Active Lists</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active site-text-lg" asp-controller="ShoppingList" asp-action="CompletedLists" asp-route-Page="1">Completed Lists</a>
                </li>
            </ul>
        </div>
        @{
            if (Model.Count > 0)
            {
                @*Landing Page Shopping List Card*@
                <div>
                    <div class="d-flex justify-content-center">
                        <div class="d-flex">
                            @foreach (var item in Model)
                            {
                                <div class="card list-page-card ms-5 me-5" style="width:23rem">
                                    <div class="d-flex flex-column align-items-end">
                                        <div>
                                            @{
                                                if (item.IsFavorited == false)
                                                {
                                                    <a class="btn btn-lg btn-light mt-2 me-1" asp-controller="ShoppingList" asp-action="SwitchIsFavorited" asp-route-ListId="@item.Id" asp-route-OldStatus="@item.IsFavorited" asp-route-Page="@ViewBag.Page">
                                                        <i class="bi bi-heart"></i>
                                                    </a>
                                                }
                                                else
                                                {
                                                    <a class="btn btn-lg btn-light mt-2 me-1" asp-controller="ShoppingList" asp-action="SwitchIsFavorited" asp-route-ListId="@item.Id" asp-route-OldStatus="@item.IsFavorited" asp-route-Page="@ViewBag.Page">
                                                        <i class="bi bi-heart-fill"></i>
                                                    </a>
                                                }
                                            }
                                        </div>
                                        @{
                                            if(ListImages[item.Id] != null)
                                            {
                                                <div class="ms-1 me-1 mb-5"><img src="@ListImages[item.Id]" class="card-img-top mx-auto" style="width:100%"></div>
                                            }

                                            else
                                            {
                                                <div class="ms-1 me-1 mb-5"><img src="/empty-list.png" class="card-img-top mx-auto" style="width:100%"></div>
                                            }
                                        }
                                    </div>
                                    <div class="card-body" style="background-color:#212121">
                                        <div class="d-flex flex-column">
                                            <h5 class="card-title site-text">@item.Name</h5>
                                            <div class="d-flex">
                                                <div class="flex-grow-1">
                                                    <a class="btn btn-light btn-lg" asp-controller="ShoppingListContent" asp-action="Index" asp-route-ListId="@item.Id" asp-route-SubcategoryId="0"><i class="bi bi-bag-plus-fill"></i></a>
                                                    <a class="btn btn-light btn-lg ms-2" asp-controller="ShoppingListContent" asp-action="ActiveListSummary" asp-route-ListId="@item.Id"><i class="bi bi-list-ul"></i></a>
                                                </div>
                                                <div><a class="btn btn-light btn-lg ms-2" asp-action="DeleteShoppingList" asp-route-ListId="@item.Id" asp-route-ReturnAction="ActiveLists"><i class="bi bi-trash3-fill"></i></a></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
                @*Shopping List Paginator*@
                <div>
                    <nav class="home-page-paginator mt-4">
                        <ul class="pagination justify-content-center">
                            <li class="page-item">
                                <a class="list-page-paginator site-text-lg me-4" href="#" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            @{
                                for (int i = 1; i <= ViewBag.PaginatorSize; i++)
                                {
                                    <li class="page-item"><a class="list-page-paginator site-text-lg ms-3 me-3" href=@Html.Raw("/?Page="+i)>@i</a></li>
                                }
                            }
                            <li class="page-item">
                                <a class="list-page-paginator site-text-lg ms-4" href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            }
            else
            {
                <div class="mx-auto my-auto">
                <img class="w-100" src="/active-list-not-found.png" />
                </div>
            }
        }
    </div>
</div>

Views/ShoppingList/CompletedLists.cshtml
@model List<Swiftshop.Models.ShoppingList>
@{
    ViewData["Title"] = "Home Page";
    Dictionary<string, string> ListImages = ViewBag.ListImages;
}

<div class="container">
    <div class="d-flex flex-column">
        <div class="d-inline-flex justify-content-between mb-5 list-page-navbar">
            <div class="ms-4 mt-4 mb-4"><h2 class="site-text">Completed Shopping Lists</h2></div>
            <!--List Type Navigation Bar-->
            <ul class="nav my-auto">
                <li class="nav-item">
                    <a class="nav-link active site-text-lg" asp-controller="ShoppingList" asp-action="ActiveLists" asp-route-Page="1">Active Lists</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled site-text-lg" aria-disabled="true">Completed Lists</a>
                </li>
            </ul>
        </div>
        @{
            if (Model.Count > 0)
            {
                @*Shopping List Card*@
                <div>
                    <div class="d-flex justify-content-center">
                        <div class="d-flex">
                            @foreach (var item in Model)
                            {
                                <div class="card list-page-card mt-2 ms-5 me-5" style="width:23rem;">
                                        @{
                                            if(ListImages[item.Id] != null)
                                            {
                                                <div class="ms-1 me-1 mt-5 mb-5" style="background:none"><img src="@ListImages[item.Id]" class="card-img-top mx-auto" style="width:100%"></div>
                                            }

                                            else
                                            {
                                                <div class="ms-1 me-1 mt-5 mb-5"><img src="/empty-list.png" class="card-img-top mx-auto" style="width:100%"></div>
                                            }
                                        }
                                    <div class="card-body" style="background-color:#212121">
                                        <div class="d-flex flex-column">
                                            <h5 class="card-title site-text">@item.Name</h5>
                                            <div class="d-flex">
                                                <a asp-controller="ShoppingListContent" asp-action="CompletedListSummary" asp-route-ListId="@item.Id" class="btn btn-light btn-lg"><i class="bi bi-list-ul"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
                @*Shopping List Paginator*@
                <div>
                    <nav class="home-page-paginator mt-4">
                        <ul class="pagination justify-content-center">
                            <li class="page-item">
                                <a class="list-page-paginator site-text-lg me-4" href="#" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            @{
                                for (int i = 1; i <= ViewBag.PaginatorSize; i++)
                                {
                                    <li class="page-item"><a class="list-page-paginator site-text-lg ms-3 me-3" href=@Html.Raw("CompletedLists/?Page="+i)>@i</a></li>
                                }
                            }
                            <li class="page-item">
                                <a class="list-page-paginator site-text-lg ms-4" href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            }
            else
            {
                <div class="mx-auto my-auto">
                    <img src="/complete-list-not-found.png" />
                </div>
            }
        }
    </div>
</div>